<a href="https://colab.research.google.com/github/igquinteroch/data-analysis/blob/master/pandas-exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Exercises

In [1]:
# Import pandas
import pandas as pd

In [2]:
# Creating a series of three different colors
colors = pd.Series(["Black", "White", "Blue"])
colors

0    Black
1    White
2     Blue
dtype: object

In [3]:
# Checking the type
print(type(colors))

<class 'pandas.core.series.Series'>

In [50]:
# Creating a series of three different car types
cars = pd.Series(["Tesla", "Audi", "Aston Martin"])
cars

0           Tesla
1            Audi
2    Aston Martin
dtype: object

In [53]:
# Combining the Series of cars and colours into a DataFrame
cars_data = pd.DataFrame({"Car make": cars, "Color": colors})
cars_data

       Car make  Color
0         Tesla  Black
1          Audi  White
2  Aston Martin   Blue

In [55]:
# Importing a DataFrame
data = "https://raw.githubusercontent.com/igquinteroch/data-analysis/master/car-sales.csv"

car_sales = pd.read_csv(data)
car_sales.head(5)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [56]:
# Finding the different datatypes of the car data DataFrame
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [57]:
# Describing the current car sales DataFrame using describe() method
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [58]:
# Getting more information about the DataFrame using info() method
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 528.0+ bytes

**Note:** The information in 'Price' column is not numeric.

### Manipulating data

In [60]:
# Creating a Series and finding the mean of them
numbers = pd.Series([12345, 47325, 67625])
numbers.mean()

42431.666666666664

In [61]:
# Finding the sum of the Series created
numbers.sum()

127295

In [62]:
# Listing out all the column names of the car sales DataFrame
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [63]:
# Finding the length of the car sales DataFrame
len(car_sales)

10

In [65]:
# Showing the first 5 rows of the car sales DataFrame
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [66]:
# Showing the first 7 rows of the car sales DataFrame
car_sales.head(7)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00

In [67]:
# Showing the bottom 5 rows of the car sales DataFrame
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [69]:
# Using .loc to select the row at index 3 of the car sales DataFrame
car_sales.loc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [70]:
# Using .iloc to select the row at position 3 of the car sales DataFrame
car_sales.iloc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

**Note:**

* loc function selects rows and columns with specific labels.
* iloc function selects rows and columns at specific integer positions.

In [71]:
# Selecting the "Odometer (KM)" column from the car sales DataFrame
car_sales["Odometer (KM)"]

0    150043
1     87899
2     32549
3     11179
4    213095
5     99213
6     45698
7     54738
8     60000
9     31600
Name: Odometer (KM), dtype: int64

In [72]:
# Finding the mean of the "Odometer (KM)" column in the car sales DataFrame
car_sales["Odometer (KM)"].mean()

78601.4

In [75]:
# Selecting the rows with over 100,000 kilometers on the Odometer
car_sales[car_sales["Odometer (KM)"] > 100000]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
4  Nissan  White         213095      4  $3,500.00

In [76]:
# Creating a crosstab of the Make and Doors columns
pd.crosstab(car_sales['Make'], car_sales["Doors"])

Doors   3  4  5
Make
BMW     0  0  1
Honda   0  3  0
Nissan  0  2  0
Toyota  1  3  0

In [25]:
# Group columns of the car sales DataFrame by the Make column and find the average

In [26]:
# Import Matplotlib and create a plot of the Odometer column
# Don't forget to use %matplotlib inline

In [27]:
# Create a histogram of the Odometer column using hist()

In [28]:
# Try to plot the Price column using plot()

Why didn't it work? Can you think of a solution?

You might want to search for "how to convert a pandas string column to numbers".

And if you're still stuck, check out this [Stack Overflow question and answer on turning a price column into integers](https://stackoverflow.com/questions/44469313/price-column-object-to-int-in-pandas).

See how you can provide the example code there to the problem here.

In [29]:
# Remove the punctuation from price column

In [30]:
# Check the changes to the price column

In [31]:
# Remove the two extra zeros at the end of the price column

In [32]:
# Check the changes to the Price column

In [33]:
# Change the datatype of the Price column to integers

In [34]:
# Lower the strings of the Make column

If you check the car sales DataFrame, you'll notice the Make column hasn't been lowered.

How could you make these changes permanent?

Try it out.

In [35]:
# Make lowering the case of the Make column permanent

In [36]:
# Check the car sales DataFrame

Notice how the Make column stays lowered after reassigning.

Now let's deal with missing data.

In [37]:
# Import the car sales DataFrame with missing data ("../data/car-sales-missing-data.csv")


# Check out the new DataFrame

Notice the missing values are represented as `NaN` in pandas DataFrames.

Let's try fill them.

In [38]:
# Fill the Odometer column missing values with the mean of the column inplace

In [39]:
# View the car sales missing DataFrame and verify the changes

In [40]:
# Remove the rest of the missing data inplace

In [41]:
# Verify the missing values are removed by viewing the DataFrame

We'll now start to add columns to our DataFrame.

In [42]:
# Create a "Seats" column where every row has a value of 5

In [43]:
# Create a column called "Engine Size" with random values between 1.3 and 4.5
# Remember: If you're doing it from a Python list, the list has to be the same length
# as the DataFrame

In [44]:
# Create a column which represents the price of a car per kilometer
# Then view the DataFrame

In [45]:
# Remove the last column you added using .drop()

In [46]:
# Shuffle the DataFrame using sample() with the frac parameter set to 1
# Save the the shuffled DataFrame to a new variable

Notice how the index numbers get moved around. The [`sample()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html) function is a great way to get random samples from your DataFrame. It's also another great way to shuffle the rows by setting `frac=1`.

In [47]:
# Reset the indexes of the shuffled DataFrame

Notice the index numbers have been changed to have order (start from 0).

In [48]:
# Change the Odometer values from kilometers to miles using a Lambda function
# Then view the DataFrame

In [49]:
# Change the title of the Odometer (KM) to represent miles instead of kilometers